# Generated by Django 5.0 on 2024-07-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='default_rating',
            field=models.FloatField(default=2.5),
        ),
    ]
